name: build Custom

on:
    workflow_dispatch:
      inputs:
        KSU:
          required: true
          type: choice
          description: "KSU Forks"
          default: "RESUKISU"
          options:
            - 'KSU'
            - 'SUKISU'
            - 'NEXT'
            - 'WILD'
            - 'RKSU'
            - 'YCRKSU'
            - 'XXKSU'
            - 'RESUKISU'
        UPLOAD_TO_GH:
          required: true
          type: boolean
          description: "Github Action(Turn Off If Frequently Runï¼ŒUpload to Telegram)"
          default: true
        BBG:
          type: boolean
          description: "Enable BBG"
          default: false
        SUSFS:
          type: boolean
          description: "Enable SUSFS"
          default: false
        KPM:
          type: boolean
          description: "Enable KPM"
          default: false
        mountify:
          type: boolean
          description: "Enable Mountify"
          default: false
        ZRAM:
          type: boolean
          description: "Enable lZ4 + ZSTD ZRAM"
          default: false
        fengchi:
          type: boolean
          description: "Enable Fengchi Kernel"
          default: false
jobs:
  Build-Kernel:
    name: "Build Kernel Normal"
     runs-on: ubuntu-latest
    env:
      CCACHE_COMPILERCHECK: "%compiler% -dumpmachine; %compiler% -dumpversion"
      CCACHE_NOHASHDIR: "true"
      CCACHE_HARDLINK: "true"
      CCACHE_DIR: /home/runner/.ccache  
      CCACHE_MAXSIZE: 8G
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 8192
          temp-reserve-mb: 2048
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'

      - name: Restore Ccache
        uses: actions/cache@v3
        with:
          path: /home/runner/.ccache
          key: ccache-${{ runner.os }}-${{ github.event.inputs.KSU }}-${{ github.ref }}
          restore-keys: |
            ccache-${{ runner.os }}-${{ github.event.inputs.KSU }}-

      - name: Set git config
        run: |
          git config --global user.name ${{ github.actor }}
          git config --global user.email ${{ github.actor }}@users.noreply.github.com

      - name: Install repo tool
        run: |
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/repo
          chmod a+x ~/repo
          sudo mv ~/repo /usr/local/bin/repo

      - name: Sync
        run: |
          mkdir kernel_workspace && cd kernel_workspace
          repo init -u https://github.com/OnePlusOSS/kernel_manifest.git -b oneplus/sm8750 -m oneplus_13_b.xml --depth=1
          repo sync -c -j$(nproc --all) --no-tags --no-clone-bundle --force-sync
          rm kernel_platform/common/android/abi_gki_protected_exports_* || echo "No protected exports!"
          rm kernel_platform/msm-kernel/android/abi_gki_protected_exports_* || echo "No protected exports!"
          sed -i 's/ -dirty//g' kernel_platform/common/scripts/setlocalversion
          sed -i 's/ -dirty//g' kernel_platform/msm-kernel/scripts/setlocalversion
          sed -i 's/ -dirty//g' kernel_platform/external/dtc/scripts/setlocalversion
          sed -i '$i res=$(echo "$res" | sed '\''s/-dirty//g'\'')' kernel_platform/common/scripts/setlocalversion
          sed -i '$i res=$(echo "$res" | sed '\''s/-dirty//g'\'')' kernel_platform/msm-kernel/scripts/setlocalversion
          sed -i '$i res=$(echo "$res" | sed '\''s/-dirty//g'\'')' kernel_platform/external/dtc/scripts/setlocalversion
          sed -i '$s|echo "\$res"|echo "-ogki-${{github.actor}}"|' kernel_platform/common/scripts/setlocalversion
          sed -i '$s|echo "\$res"|echo "-ogki-${{github.actor}}"|' kernel_platform/msm-kernel/scripts/setlocalversion
          sed -i '$s|echo "\$res"|echo "-ogki-${{github.actor}}"|' kernel_platform/external/dtc/scripts/setlocalversion

      - name: Get Scripts
        uses: actions/checkout@v4
        with: 
          path: scripts

      - name: Running Configure
        run: |
          cp ./scripts/scripts/configure ./kernel_workspace/
          chmod +x ./kernel_workspace/configure
          
          ARGS="--ksu-variant ${{ github.event.inputs.KSU }}"
          if [ "${{ github.event.inputs.SUSFS }}" == "true" ]; then
            ARGS+=" --susfs"
          fi
          if [ "${{ github.event.inputs.BBG }}" == "true" ]; then
            ARGS+=" --with-bbg"
          fi
          if [ "${{ github.event.inputs.KPM }}" == "true" ] && [ "${{ github.event.inputs.KSU }}" == "SUKISU" ]; then
            ARGS+=" --kpm"
          fi
          if [ "${{ github.event.inputs.mountify }}" == "true" ]; then
            ARGS+=" --mountify"
          fi
          if [ "${{ github.event.inputs.ZRAM }}" == "true" ]; then
            ARGS+=" --zram"
          fi
          if [ "${{ github.event.inputs.fengchi }}" == "true" ]; then
            ARGS+=" --fengchi"
          fi

          
          cd kernel_workspace
          ./configure $ARGS

      - name: build
        run: |
          export PATH="/usr/lib/ccache:$GITHUB_WORKSPACE/kernel_workspace/kernel_platform/prebuilts/clang/host/linux-x86/clang-r510928/bin:$PATH" 
          export PATH="/usr/lib/ccache:$PATH"
          sudo apt install libelf-dev ccache
          cd kernel_workspace/kernel_platform/common
          make -j$(nproc --all) LLVM=1 ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- CC="ccache clang" RUSTC=../../prebuilts/rust/linux-x86/1.73.0b/bin/rustc PAHOLE=../../prebuilts/kernel-build-tools/linux-x86/bin/pahole LD=ld.lld HOSTLD=ld.lld O=out KCFLAGS+=-O2  gki_defconfig all

      - name: Pack anykernel3
        run: |
         cd kernel_workspace/
         git clone https://github.com/kingmikhail/Anykernel3 --depth=1
         rm -rf Anykernel3/.git
         cp kernel_platform/common/out/arch/arm64/boot/Image.gz ./Anykernel3/Image.gz
         cd Anykernel3
         zip -q -r "../AnyKernel3_Op_ACE6.zip" ./*

      - name: Upload To Github Actions
        if: inputs.UPLOAD_TO_GH
        uses: actions/upload-artifact@v4
        with:
          name: Anykernel3
          path: kernel_workspace/AnyKernel3_Op_ACE6.zip
      
